// Code generated by protoc-gen-go.
// source: lifx.proto
// DO NOT EDIT!

/*
Package lifxproto is a generated protocol buffer package.

It is generated from these files:
	lifx.proto

It has these top-level messages:
	GetPanGateway
*/
package lifxproto

import proto "code.google.com/p/goprotobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type PacketID int32

const (
	PacketID_GETPANGATEWAY PacketID = 2
	PacketID_PANGATEWAY    PacketID = 3
	PacketID_GETBULBLABEL  PacketID = 23
	PacketID_BULBLABEL     PacketID = 25
	PacketID_GETLIGHTSTATE PacketID = 101
	PacketID_SETLIGHTCOLOR PacketID = 102
	PacketID_LIGHTSTATUS   PacketID = 107
)

var PacketID_name = map[int32]string{
	2:   "GETPANGATEWAY",
	3:   "PANGATEWAY",
	23:  "GETBULBLABEL",
	25:  "BULBLABEL",
	101: "GETLIGHTSTATE",
	102: "SETLIGHTCOLOR",
	107: "LIGHTSTATUS",
}
var PacketID_value = map[string]int32{
	"GETPANGATEWAY": 2,
	"PANGATEWAY":    3,
	"GETBULBLABEL":  23,
	"BULBLABEL":     25,
	"GETLIGHTSTATE": 101,
	"SETLIGHTCOLOR": 102,
	"LIGHTSTATUS":   107,
}

func (x PacketID) Enum() *PacketID {
	p := new(PacketID)
	*p = x
	return p
}
func (x PacketID) String() string {
	return proto.EnumName(PacketID_name, int32(x))
}
func (x *PacketID) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(PacketID_value, data, "PacketID")
	if err != nil {
		return err
	}
	*x = PacketID(value)
	return nil
}

type Reserved int32

const (
	Reserved_RESERVED1 Reserved = 0
	Reserved_RESERVED2 Reserved = 0
	Reserved_RESERVED3 Reserved = 0
	Reserved_RESERVED4 Reserved = 0
)

var Reserved_name = map[int32]string{
	0: "RESERVED1",
	// Duplicate value: 0: "RESERVED2",
	// Duplicate value: 0: "RESERVED3",
	// Duplicate value: 0: "RESERVED4",
}
var Reserved_value = map[string]int32{
	"RESERVED1": 0,
	"RESERVED2": 0,
	"RESERVED3": 0,
	"RESERVED4": 0,
}

func (x Reserved) Enum() *Reserved {
	p := new(Reserved)
	*p = x
	return p
}
func (x Reserved) String() string {
	return proto.EnumName(Reserved_name, int32(x))
}
func (x *Reserved) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Reserved_value, data, "Reserved")
	if err != nil {
		return err
	}
	*x = Reserved(value)
	return nil
}

type GetPanGateway struct {
	Size             []byte    `protobuf:"bytes,1,req,name=size" json:"size,omitempty"`
	Protocol         []byte    `protobuf:"bytes,2,req,name=protocol" json:"protocol,omitempty"`
	Reserved1        *Reserved `protobuf:"varint,3,opt,name=reserved1,enum=lifxproto.Reserved,def=0" json:"reserved1,omitempty"`
	TargetMacAddress []byte    `protobuf:"bytes,4,req,name=target_mac_address" json:"target_mac_address,omitempty"`
	Reserved2        *Reserved `protobuf:"varint,5,opt,name=reserved2,enum=lifxproto.Reserved,def=0" json:"reserved2,omitempty"`
	Site             []byte    `protobuf:"bytes,6,req,name=site" json:"site,omitempty"`
	Reserved3        *Reserved `protobuf:"varint,7,opt,name=reserved3,enum=lifxproto.Reserved,def=0" json:"reserved3,omitempty"`
	Timestamp        *uint64   `protobuf:"varint,8,req,name=timestamp" json:"timestamp,omitempty"`
	PacketType       *PacketID `protobuf:"varint,9,opt,name=packet_type,enum=lifxproto.PacketID,def=2" json:"packet_type,omitempty"`
	Reserved4        *Reserved `protobuf:"varint,10,opt,name=reserved4,enum=lifxproto.Reserved,def=0" json:"reserved4,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *GetPanGateway) Reset()         { *m = GetPanGateway{} }
func (m *GetPanGateway) String() string { return proto.CompactTextString(m) }
func (*GetPanGateway) ProtoMessage()    {}

const Default_GetPanGateway_Reserved1 Reserved = Reserved_RESERVED1
const Default_GetPanGateway_Reserved2 Reserved = Reserved_RESERVED2
const Default_GetPanGateway_Reserved3 Reserved = Reserved_RESERVED3
const Default_GetPanGateway_PacketType PacketID = PacketID_GETPANGATEWAY
const Default_GetPanGateway_Reserved4 Reserved = Reserved_RESERVED4

func (m *GetPanGateway) GetSize() []byte {
	if m != nil {
		return m.Size
	}
	return nil
}

func (m *GetPanGateway) GetProtocol() []byte {
	if m != nil {
		return m.Protocol
	}
	return nil
}

func (m *GetPanGateway) GetReserved1() Reserved {
	if m != nil && m.Reserved1 != nil {
		return *m.Reserved1
	}
	return Default_GetPanGateway_Reserved1
}

func (m *GetPanGateway) GetTargetMacAddress() []byte {
	if m != nil {
		return m.TargetMacAddress
	}
	return nil
}

func (m *GetPanGateway) GetReserved2() Reserved {
	if m != nil && m.Reserved2 != nil {
		return *m.Reserved2
	}
	return Default_GetPanGateway_Reserved2
}

func (m *GetPanGateway) GetSite() []byte {
	if m != nil {
		return m.Site
	}
	return nil
}

func (m *GetPanGateway) GetReserved3() Reserved {
	if m != nil && m.Reserved3 != nil {
		return *m.Reserved3
	}
	return Default_GetPanGateway_Reserved3
}

func (m *GetPanGateway) GetTimestamp() uint64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

func (m *GetPanGateway) GetPacketType() PacketID {
	if m != nil && m.PacketType != nil {
		return *m.PacketType
	}
	return Default_GetPanGateway_PacketType
}

func (m *GetPanGateway) GetReserved4() Reserved {
	if m != nil && m.Reserved4 != nil {
		return *m.Reserved4
	}
	return Default_GetPanGateway_Reserved4
}

func init() {
	proto.RegisterEnum("lifxproto.PacketID", PacketID_name, PacketID_value)
	proto.RegisterEnum("lifxproto.Reserved", Reserved_name, Reserved_value)
}
