// Code generated by protoc-gen-go.
// source: lifx.proto
// DO NOT EDIT!

/*
Package lifx is a generated protocol buffer package.

It is generated from these files:
	lifx.proto

It has these top-level messages:
	Packet
*/
package lifx

import proto "code.google.com/p/goprotobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type Packet struct {
	Size             []byte  `protobuf:"bytes,1,req,name=size" json:"size,omitempty"`
	Protocol         []byte  `protobuf:"bytes,2,req,name=protocol" json:"protocol,omitempty"`
	Reserved1        *uint32 `protobuf:"varint,3,req,name=reserved1" json:"reserved1,omitempty"`
	TargetMacAddress []byte  `protobuf:"bytes,4,req,name=target_mac_address" json:"target_mac_address,omitempty"`
	Reserved2        []byte  `protobuf:"bytes,5,req,name=reserved2" json:"reserved2,omitempty"`
	Site             []byte  `protobuf:"bytes,6,req,name=site" json:"site,omitempty"`
	Reserved3        []byte  `protobuf:"bytes,7,req,name=reserved3" json:"reserved3,omitempty"`
	Timestamp        *uint64 `protobuf:"varint,8,req,name=timestamp" json:"timestamp,omitempty"`
	PacketType       []byte  `protobuf:"bytes,9,req,name=packet_type" json:"packet_type,omitempty"`
	Reserved4        []byte  `protobuf:"bytes,10,req,name=reserved4" json:"reserved4,omitempty"`
	Payload          []byte  `protobuf:"bytes,11,opt,name=payload" json:"payload,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Packet) Reset()         { *m = Packet{} }
func (m *Packet) String() string { return proto.CompactTextString(m) }
func (*Packet) ProtoMessage()    {}

func (m *Packet) GetSize() []byte {
	if m != nil {
		return m.Size
	}
	return nil
}

func (m *Packet) GetProtocol() []byte {
	if m != nil {
		return m.Protocol
	}
	return nil
}

func (m *Packet) GetReserved1() uint32 {
	if m != nil && m.Reserved1 != nil {
		return *m.Reserved1
	}
	return 0
}

func (m *Packet) GetTargetMacAddress() []byte {
	if m != nil {
		return m.TargetMacAddress
	}
	return nil
}

func (m *Packet) GetReserved2() []byte {
	if m != nil {
		return m.Reserved2
	}
	return nil
}

func (m *Packet) GetSite() []byte {
	if m != nil {
		return m.Site
	}
	return nil
}

func (m *Packet) GetReserved3() []byte {
	if m != nil {
		return m.Reserved3
	}
	return nil
}

func (m *Packet) GetTimestamp() uint64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

func (m *Packet) GetPacketType() []byte {
	if m != nil {
		return m.PacketType
	}
	return nil
}

func (m *Packet) GetReserved4() []byte {
	if m != nil {
		return m.Reserved4
	}
	return nil
}

func (m *Packet) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func init() {
}
